add course and subcourse delete along with tests
corona-school/backend pull request #1003
Opened 2024-02-18 19:26 UTC by paul-jaworski

2024-02-18 19:28 UTC, paul-jaworski commented
I need some help. Where must I delete the subcourse from? Apparantly the subcourse id is referenced in multiple table, i.e.:
![grafik](https://github.com/corona-school/backend/assets/52598637/b0c626e8-9c2c-46ea-8ae2-ed60fa3348ef)

2024-02-18 21:40 UTC, Jonasdoubleyou commented
https://github.com/corona-school/backend/blob/master/prisma/schema.prisma every entity that has a courseId or subcourseId

2024-02-18 21:44 UTC, Jonasdoubleyou requested changes

2024-02-18 21:44 UTC, Jonasdoubleyou commented on graphql/course/mutations.ts
> +        if (course) {
How can course be null?

2024-02-18 21:44 UTC, Jonasdoubleyou commented on graphql/course/mutations.ts
> +            const result = await prisma.course.delete({ where: { id: courseId } });
Move this to common/course

Also please implement checks for the prerequisites mentioned in https://github.com/corona-school/project-user/issues/1048

2024-03-19 20:05 UTC, paul-jaworski commented
@Jonasdoubleyou I need your help :D Somehow the prisma calls to delete subcourses do not get executed. Is there a possibility to execute a single test to observe the sql output?

2024-03-28 10:46 UTC, realmayus requested changes

2024-03-28 10:46 UTC, realmayus commented on graphql/subcourse/mutations.ts
> +        deleteSubcourse(subcourse);
this is missing an `await` @paul-jaworski

2024-03-28 10:46 UTC, realmayus commented on common/courses/states.ts
> +    console.log('deleteSubcourse function finished');
Please use `logger.info` for logging

2024-03-29 13:00 UTC, paul-jaworski commented
So the Delete Course is running through successfully. However it appears that it has sideeffects on other tests (in particular the Create an appointment for a subcourse test.)

Should I remove the Delete Course test or make any other changes or remove it alltogether?

2024-03-30 15:29 UTC, Jonasdoubleyou commented
Either reorder the tests so that the course is deleted as the last test, or alternatively create a new course for the test

2024-03-30 16:04 UTC, Jonasdoubleyou commented on integration-tests/07_course.ts
> +        .request(
Can just use requestShallFail

2024-03-30 16:04 UTC, Jonasdoubleyou commented on integration-tests/07_course.ts
> +import { ValidationError } from 'apollo-server-express';
unused import?

2024-03-30 16:04 UTC, Jonasdoubleyou commented on graphql/course/mutations.ts
> +        logger.info(`Course (${courseId}) deleted successfully`);
I'd move the logging into the function in commons

2024-03-30 16:04 UTC, Jonasdoubleyou commented on common/courses/states.ts
> +    return new Promise<Decision>((resolve) => {
why the promise?

2024-03-30 16:04 UTC, Jonasdoubleyou commented on common/courses/states.ts
> +        return { allowed: true, reason: `Course ${course.id} has no subcourses` };
The decision.reason is supposed to be "machine readable", i.e. a constant string where we can then maintain error message translations in the frontend. So it should rather be { allowed: false, reason: "has-subcourse" }, { allowed: true }

2024-03-31 08:15 UTC, paul-jaworski commented
> Either reorder the tests so that the course is deleted as the last test, or alternatively create a new course for the test

How can I determinie the execution order of the test? I do not See any test framework being used that I can google for :D

2024-03-31 09:18 UTC, Jonasdoubleyou commented
For now test execution is basically sequential, so just create a new file and import it in https://github.com/corona-school/backend/blob/master/integration-tests/index.ts

2024-03-31 15:14 UTC, Jonasdoubleyou reviewed
one last round :)

2024-03-31 15:14 UTC, Jonasdoubleyou commented on common/courses/states.ts
> +    const deleteResult = await prisma.subcourse.delete({ where: { id: subcourse.id } });
Logging?

2024-03-31 15:14 UTC, Jonasdoubleyou commented on integration-tests/07_course.ts
> +        .then(async () => {
.then not needed

2024-03-31 15:14 UTC, Jonasdoubleyou commented on integration-tests/07_course.ts
> +        .then(() => assert.ok('Successfully deleted empty course'))
.then and .catch not needed

2024-04-01 15:02 UTC, Jonasdoubleyou submitted a review, later dismissed

2024-04-01 18:01 UTC, Jonasdoubleyou approved these changes

2024-04-01 18:06 UTC, Jonasdoubleyou requested changes
wait, why do you delete .env.example?

2024-04-02 06:56 UTC, paul-jaworski commented
> wait, why do you delete .env.example?

ops you are right tnak you

2024-04-02 11:12 UTC, Jonasdoubleyou approved these changes

2024-04-02 11:13 UTC, merged