drop verifiedAt column
corona-school/backend pull request #1109
Opened 2024-06-29 09:07 UTC by paul-jaworski

2024-07-02 09:58 UTC, JeangelLF requested changes
Thanks for the PR.

I left some comments about some changes that need to be made.

2024-07-02 09:58 UTC, JeangelLF commented on common/courses/notifications.ts
> +import { notNull } from 'jest-mock-extended';
This import is not needed, we can remove it.

2024-07-02 09:58 UTC, JeangelLF commented on common/notification/index.ts
> -        // --------------- Send out Notifications to send directly --------------------------------------
Why did you remove this whole block? 🤔  Let's bring it back and fix the parts that use the `verification` field.

2024-07-02 09:58 UTC, JeangelLF commented on prisma/migrations/0_init/migration.sql
> -    "verification" VARCHAR,
Undo the changes to this file. It doesn't make sense to do this on the migration files.

2024-07-02 09:58 UTC, JeangelLF commented on prisma/schema.prisma
>    lastname                     String?                 @db.VarChar
Also, undo the changes to this file. The idea is that we first stop using the verification column in favor of `verifiedAt`.
The part of dropping the verification column from the DB should be done in a separate pull request :)

2024-07-02 09:58 UTC, JeangelLF commented on common/pupil/registration.ts
>              verification,
No need to drop this for now, we can do it in a separate PR (the same that drops the column from the `schema.prisma`)

2024-07-02 09:58 UTC, JeangelLF commented on common/pupil/registration.ts
>      await logTransaction('verificationRequets', userForPupil(pupil), {});
No need to drop this.

2024-07-02 09:58 UTC, JeangelLF commented on common/pupil/token.ts
>      if (pupil.verification !== null) {
We have to change it to check if `verifiedAt` is not set

2024-07-02 09:58 UTC, JeangelLF commented on common/student/registration.ts
>              verification: uuidv4(),
Not yet.

2024-07-04 06:12 UTC, JeangelLF requested changes
Thanks, most of it was already fixed. I left again some comments about some adjustments we have to make.

Here on Github, on the `Files changed` tab, you can check by yourself the final changes of the pull request. Make sure that all of them are intentional :)

2024-07-04 06:12 UTC, JeangelLF commented on common/pupil/registration.ts
>              verification,
Could you remove the comment or change it to `TODO: Remove after migration`?
You can leave PR Notes as a comments here in Github.

2024-07-04 06:12 UTC, JeangelLF commented on common/pupil/registration.ts
>      await logTransaction('verificationRequets', userForPupil(pupil), {});
Could you remove the comment or change it to `TODO: Remove after migration`?

2024-07-04 06:12 UTC, JeangelLF commented on common/pupil/token.ts
>      if (pupil.verification !== null) {
We still need to change this validation to check if verified is not set @paul-jaworski
Also, remove the comment

2024-07-04 06:12 UTC, JeangelLF commented on common/student/registration.ts
>              verification: uuidv4(),
Could you remove the comment or change it to `TODO: Remove after migration`?

2024-07-04 06:12 UTC, JeangelLF commented on prisma/migrations/0_init/migration.sql
> -    "verification" VARCHAR,
There are still some order/formatting changes. Could you also fix those?
Ideally, we leave this file untouched

2024-07-04 06:12 UTC, JeangelLF commented on prisma/schema.prisma
>    lastname                     String?                 @db.VarChar
Here there are also changes with the ordering / formatting. Could you also fix those?

2025-02-25 11:31 UTC, Jonasdoubleyou approved these changes

2025-02-26 10:14 UTC, merged