feat: add chat meta data
corona-school/backend pull request #690
Opened 2023-06-14 06:58 UTC by LomyW

2023-06-16 10:59 UTC, timidak reviewed
Just a few remarks 👍🏻

2023-06-16 10:59 UTC, timidak commented on common/chat/conversation.ts
>  const apiKey = process.env.TALKJS_API_KEY;
These type of constants should be written in capital letters in my opinion.

2023-06-16 10:59 UTC, timidak commented on common/chat/conversation.ts
>  const apiKey = process.env.TALKJS_API_KEY;
```ts
const TALKJS_API_URL = `https://api.talkjs.com/v1/${process.env.TALKJS_APP_ID}`;
const ... = `${talkjsApiUrl}/conversations`;
const TALKJS_API_KEY = process.env.TALKJS_API_KEY;
```

2023-06-16 10:59 UTC, timidak commented on common/chat/conversation.ts
> +        case 'oneOnOne':
way better like this

2023-06-16 13:20 UTC, LomyW commented on common/chat/conversation.ts
> +// TODO: remove subcourse from custom prop, if subcourse cancel...
will be done in the other PR to reactivate a chat

2023-06-27 16:02 UTC, timidak requested changes
Just a few points from my side! Nice job so far, Lomy! 💯

2023-06-27 16:02 UTC, timidak commented on graphql/chat/mutations.ts
> +        const contact = myContacts.find((c) => c.user.userID === contactUserId);
What if no contact was found in the myContacts because somebody just lost the contact status or somebody is hitting the api?

2023-06-27 16:02 UTC, timidak commented on graphql/chat/mutations.ts
> +        const conversation = await getOrCreateOneOnOneConversation([user, contactUser], conversationInfos, ContactReason.CONTACT);
Move this into common

2023-06-27 16:02 UTC, timidak commented on integration-tests/matching.ts
> +        response: {}, // TODO: Mock properly
Shouldn't we do this now?

2023-06-27 17:54 UTC, Jonasdoubleyou commented on graphql/chat/mutations.ts
> +        const allowed = await checkIfSubcourseParticipation([user.userID, memberUserId]);
The problem is that we do not have a direct relationship between different users of the same course, and modelling those as roles is kinda unituitive, i.e. INSTRUCTOR_OF_PARTICIPANT or PARTICIPANT_OF_SAME_COURSE. I think this is fine for now, can still refactor if patterns emerge

2023-06-29 18:58 UTC, timidak approved these changes
LGTM 👍🏻

2023-07-03 11:43 UTC, merged